DROP TABLE IF EXISTS ntn_metadata CASCADE;
DROP TABLE IF EXISTS ntn_all CASCADE;


CREATE TABLE ntn_metadata(
	network VARCHAR(30) NOT NULL, 
	siteID VARCHAR(30) NOT NULL PRIMARY KEY,
	siteName VARCHAR(100) NOT NULL,
	status VARCHAR(30) NOT NULL,
	startDate DATE NOT NULL,
	stopDate VARCHAR(30) NOT NULL,
	county VARCHAR(30) NOT NULL,
	state VARCHAR(30) NOT NULL,
	latitude VARCHAR(30) NOT NULL,
	longitude VARCHAR(30) NOT NULL,
	elevation VARCHAR(30) NOT NULL,
	stateName VARCHAR(30) NOT NULL,
	siteClass VARCHAR(30) NOT NULL
);

CREATE TABLE ntn_all(
	siteID VARCHAR(30) NOT NULL PRIMARY KEY,	
	seas VARCHAR(30) NOT NULL,
	yr INT NOT NULL,
	Criteria1 INT NOT NULL,
	Criteria2 INT NOT NULL,
	Criteria3 INT NOT NULL,
	CA VARCHAR(30) NOT NULL,
	Mg VARCHAR(30) NOT NULL,
	K VARCHAR(30) NOT NULL,
	Na VARCHAR(30) NOT NULL,
	NH4 VARCHAR(30) NOT NULL,
	NO3 VARCHAR(30) NOT NULL,
	Cl VARCHAR(30) NOT NULL,
	SO4	VARCHAR(30) NOT NULL,
	H VARCHAR(30) NOT NULL,	
	Conduc VARCHAR(30) NOT NULL,	
	svol VARCHAR(30) NOT NULL,	
	ppt VARCHAR(30) NOT NULL,
	fullChemLab	INT NOT NULL,
	daysSample INT NOT NULL,	
	startDate DATE NOT NULL,	
	lastDate DATE NOT NULL
);

SELECT * FROM ntn_metadata;
SELECT * FROM ntn_all;